[alias]
xtest = "nextest run --workspace"
coverage = "llvm-cov nextest --workspace --summary-only --fail-under-lines 40"
coverage-ci = "llvm-cov nextest --workspace --profile ci --summary-only --fail-under-lines 40"

[build]
rustflags = ["-Ctarget-cpu=x86-64"]

[registries.crates-io]
protocol = "sparse"
