name: Tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            os: ubuntu-latest
            rustflags: ""
          - name: windows
            os: windows-latest
            rustflags: ""
          - name: macos-x86_64
            os: macos-15-intel
            rustflags: ""
          - name: macos-aarch64
            os: macos-15
            rustflags: -Ctarget-feature=-sha3

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          key: stable-${{ matrix.name }}

      - name: Run tests
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
        run: cargo test --workspace --all-targets --locked
