name: Tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          key: stable-${{ matrix.os }}

      - name: Run tests
        run: cargo test --workspace --all-targets --locked
